return {
  --   'olimorris/codecompanion.nvim',
  --   dependencies = {
  --     'nvim-lua/plenary.nvim',
  --     'nvim-treesitter/nvim-treesitter',
  --
  --     {
  --       'zbirenbaum/copilot.lua',
  --       config = function()
  --         require('copilot').setup {
  --           panel = {
  --             auto_refresh = false,
  --             keymap = {
  --               accept = '<CR>',
  --               jump_prev = '[[',
  --               jump_next = ']]',
  --               refresh = 'gr',
  --               open = '<M-CR>',
  --             },
  --           },
  --           suggestion = {
  --             auto_trigger = true,
  --             keymap = {
  --               accept = '<M-l>',
  --               prev = '<M-[>',
  --               next = '<M-]>',
  --               dismiss = '<C-]>',
  --             },
  --           },
  --         }
  --       end,
  --     },
  --   },
  --   config = true,
  --   opts = {
  --     strategies = {
  --       chat = {
  --         adapter = 'copilot',
  --       },
  --       inline = {
  --         adapter = 'copilot',
  --       },
  --     },
  --   },
}
