return {
  -- 'zbirenbaum/copilot.lua',
  -- cmd = 'Copilot',
  -- requires = {
  --   'copilotlsp-nvim/copilot-lsp', -- (optional) for NES functionality
  -- },
  -- event = 'InsertEnter',
  -- opts = {
  --   panel = {
  --     auto_refresh = false,
  --     keymap = {
  --       accept = '<CR>',
  --       jump_prev = '[[',
  --       jump_next = ']]',
  --       refresh = 'gr',
  --       open = '<M-CR>',
  --     },
  --   },
  --   suggestion = {
  --     auto_trigger = true,
  --     keymap = {
  --       accept = '<Tab>',
  --       prev = '<D-[>',
  --       next = '<D-]>',
  --       dismiss = '<C-]>',
  --     },
  --   },
  -- },
}
